name=PropertiesConfig
appenders=console, rollingFile

appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

appender.rollingFile.type=RollingFile
appender.rollingFile.name=FILE
appender.rollingFile.fileName=logs/log-tracking.log
appender.rollingFile.filePattern=logs/log-tracking-%d{yyyy-MM-dd}-%i.log.gz
appender.rollingFile.layout.type=PatternLayout
appender.rollingFile.layout.pattern=[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n

appender.rollingFile.policies.type=Policies
appender.rollingFile.policies.size.type=SizeBasedTriggeringPolicy
appender.rollingFile.policies.size.size=20MB

appender.rollingFile.strategy.type=DefaultRolloverStrategy
appender.rollingFile.strategy.max=50

rootLogger.level=WARN
rootLogger.appenderRefs=stdout, file
rootLogger.appenderRef.stdout.ref=STDOUT
rootLogger.appenderRef.file.ref=FILE

logger.co.com.wdgg.name=co.com.wdgg
logger.co.com.wdgg.level=DEBUG
logger.co.com.wdgg.appenderRefs=stdout, file
logger.co.com.wdgg.appenderRef.stdout.ref=STDOUT
logger.co.com.wdgg.appenderRef.file.ref=FILE